name: Scheduled Deployment every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
    # - cron: '0 16 * * 1-5'  # UTC time for 5 PM CET

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: |
          curl -X POST 'https://api.render.com/deploy/srv-cosfupi1hbls73fkanpg?key=JZNn_8s9gAU'
