name: Daily 5pm tweet

on:
  schedule:
    - cron: '0 16 * * 1-5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: |
          curl -X POST 'https://api.render.com/deploy/srv-cosfupi1hbls73fkanpg?key=JZNn_8s9gAU'
